<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BE_Mobile.Models\BE_Mobile.Models.csproj" />
    <ProjectReference Include="..\BE_Mobile.Services\BE_Mobile.Services.csproj" />
  </ItemGroup>

</Project>
